Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProductsManager.Controllers;
using ProductsManager.Models;
using ProductsManager.Repository;


[Route("report")]
public class ReportController : Controller
{
    private ILogger<InitializeDatabaseController> _logger;
    private readonly WarehouseDbContext _context;
    private readonly IWarehouseItemRepository _repo;

    public ReportController(WarehouseDbContext context, IWarehouseItemRepository repo, ILogger<InitializeDatabaseController> logger)
    {
        _context = context;
        _repo = repo;
        _logger = logger;  
    }

    [HttpGet("main")]
    public async Task<IActionResult> Index(CancellationToken token)
    {
        WarehouseViewModel model = new();
        List<WarehouseItem> result = await _repo.GetItemsAsync(token);
        model = await PopulateItemsAsync(result, token);

        return View(model);
    }

    [HttpGet("filters")]
    public async Task<IActionResult> FilterWarehouseItems(string searchParam, string? productName, int? status, int? suppliersid, string? start_add, string? end_add, string? start_upd, string? end_upd, CancellationToken token)
    {
        WarehouseViewModel model = new();
        var result = await _repo.GetItemsByFiltersAsync(searchParam, productName, status, suppliersid, start_add, end_add, start_upd, end_upd, token);
        model = await PopulateItemsAsync(result, token);
        model.Filters = new WarehouseItemFilters()
        {
            Status = status,
            SuppliersId = suppliersid,
            StartAddSate = start_add,
            EndAddDate = end_add,
            EndUpdDate = end_upd,
            StartUpdDate = start_upd,
            ProductName = productName,
            SearchString = searchParam
        };
       
        return View("Index", model);
    }

    [HttpGet("search")]
    public async Task<IActionResult> SearchWarehouseItems(string searchParam, CancellationToken token)
    {
        WarehouseViewModel model = new();
        if (string.IsNullOrEmpty(searchParam))
        {
            var result = await _repo.GetItemsAsync(token);
            model = await PopulateItemsAsync(result, token);
        }
        else
        {
            var result = await _repo.GetItemsBySearchAsync(searchParam, token);
            model = await PopulateItemsAsync(result, token);
        }

        model.SearchString = searchParam;

        return View("Index", model);
    }

    private async Task<WarehouseViewModel> PopulateItemsAsync(List<WarehouseItem> items, CancellationToken token)
    {
        WarehouseViewModel model = new();
        model.Items = items;
        var allItems = await _repo.GetItemsAsync(token);
        model.Products = allItems.Select(item => item.Name).Distinct().ToList();
        model.TotalRecords = items.Count;
        model.TotalProducts = items.Select(item => item.Name).Distinct().Count();
        model.TotalPrice = items.Sum(item => item.Price);
        model.TotalQuantity = items.Sum(item => item.Quantity);
        model.TotalSuppliers = items.Select(item => item.SuppliersId).Distinct().Count();
        model.Suppliers = await _repo.GetSuppliersAsync(token);
        model.Statuses = Enum.GetValues<Statuses>()
            .Select(e => new SelectListItem
            {
                Value = ((int)e).ToString(),
                Text = e.ToString()
            });

        return model;
    }
}

Controllers/WarehouseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProductsManager.Controllers;
using ProductsManager.Models;
using ProductsManager.Repository;

[Route("warehouse")]
public class WarehouseController : Controller
{
    private ILogger<InitializeDatabaseController> _logger;
    private readonly WarehouseDbContext _context;
    private readonly IWarehouseItemRepository _repo;

    public WarehouseController(WarehouseDbContext context, IWarehouseItemRepository repo, ILogger<InitializeDatabaseController> logger)
    {
        _context = context;
        _repo = repo;
        _logger = logger;  
    }

    [HttpGet("main")]
    public async Task<IActionResult> Index(CancellationToken token)
    {
        WarehouseViewModel model = new();
        var result = await _repo.GetItemsAsync(token);
        model.Items = result;
        model.Suppliers = await _repo.GetSuppliersAsync(token);
        model.Statuses = Enum.GetValues<Statuses>()
            .Select(e => new SelectListItem
            {
                Value = ((int)e).ToString(),
                Text = e.ToString()
            });
        
        return View(model);
    }

    [HttpPost("create")]
    public async Task<IActionResult> Create([Bind("Name,Quantity,Price,SuppliersId,UniqueCode,Status")] GetWarehouseItemRequest item, CancellationToken token)
    {
        try
        {
            await _repo.AddItemAsync(item, token);
            TempData["Success"] = GlobalMessages.ItemCreationSuccess;

            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex,ex.Message);
            TempData["Error"] = GlobalMessages.ItemCreationError;
            return RedirectToAction("Index");
        }
    }

    [HttpPost("edit")]
    public async Task<IActionResult> Edit([FromBody] GetWarehouseItemRequest reqItem, CancellationToken token)
    {
        try
        {
            var oldItem = await _repo.GetSingleItemAsync(reqItem.Id, token);
            if (oldItem == null)
            {
                TempData["Error"] = GlobalMessages.ItemNotFound;
                return RedirectToAction("Index");
            }
            await _repo.UpdateItemAsync(reqItem, oldItem, token);
            TempData["Success"] = GlobalMessages.ItemUpdateSuccess;

            return Ok(new { message = GlobalMessages.ItemUpdateSuccess });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, ex.Message);
            return Ok(new { Message = GlobalMessages.ItemUpdateError });
        }
    }

    [HttpGet("get-item")]
    public async Task<IActionResult> GetItem(int id, CancellationToken token)
    {
        try
        {
            WarehouseViewModel model = new();
            model.Item = await _repo.GetSingleItemAsync(id, token);

            return Ok(model.Item);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, ex.Message);
            return Ok(new { Message = GlobalMessages.ItemCancellationError });
        }
    }

    [HttpPost("delete")]
    public async Task<IActionResult> Delete([Bind("cbitems")] string cbitems, CancellationToken token)
    {
        if (string.IsNullOrEmpty(cbitems))
        {
            return NotFound();
        }
        await _repo.DeleteMultiItemsAsync(cbitems, token);
        TempData["Success"] = GlobalMessages.ItemDeletionSuccess;

        return RedirectToAction("Index");
    }

    [HttpGet("filters")]
    public async Task<IActionResult> FilterWarehouseItems(string? searchParam, string? productName, int? status, int? suppliersid, string? start, string? end, string? startUpd, string? endUpd, CancellationToken token)
    {
        WarehouseViewModel model = new();
        model.Items = await _repo.GetItemsByFiltersAsync(searchParam, productName, status, suppliersid, start, end, startUpd, endUpd, token);
        model.Suppliers = await _repo.GetSuppliersAsync(token);
        model.Statuses = Enum.GetValues<Statuses>()
            .Select(e => new SelectListItem
            {
                Value = ((int)e).ToString(),
                Text = e.ToString()
            });

        model.Filters = new WarehouseItemFilters()
        {
            Status = status,
            SuppliersId = suppliersid,
            StartAddSate = start,
            EndAddDate = end,
            SearchString = searchParam
        };

        return View("Index", model);
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductsManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductsManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProductsManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Report</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProductsManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

</body>
</html>